### ISSUE TITLE
Error on arbitrage tx: pending transaction with same hash already exists

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Watcher#26]
This error appears repetitively once it appears for the first time. 

The solution is very easy: add and remove from the queue using amount as the arbitrage transaction identifier

EDIT: Mmm, actually not that easy to fix :thinking:  Since this error also shows up just when launching the node, before the queue is formed. Very strange error, to be honest

**Comment by Bitcoinera** [comment]
Don't know if there is an easy way to prevent this. Maybe not so important

**Comment by jamiemadrox779** [comment]
This happend only because the watcher was restarted while a tx was still pending
